### ISSUE TITLE
Bug: Could not register project in codealike server.

### ISSUE THREAD

**Issue by Marimout** [Codealike/Codealike-VSCode#7]
Hello,

When I put the token, I got the error message "Could not register project in codealike server".

VS Code: February 2019 (version 1.32)

Can you please look at it?

Thanks.

**Comment by soke1556** [comment]
@Marimout Can you please describe if this happens to all folder/workspaces or only to a particular one? Thanks.

**Comment by Marimout** [comment]
I tried with a .NET and a Javascript project, it doesn't work for both.

**Comment by soke1556** [comment]
Please, try to do this and let me know if the problem persists:
1) Close VSCode.
2) Delete file codealike.json from folder/workspace (delete also in subfolders if it's present).
3) Run VSCode.

After that, Codealike should begin tracking. Let me know if it works or not. Thanks.

**Comment by Marimout** [comment]
Thank you, that solved my problem.

I'll close the issue then.
